# Generated by Django 2.2.3 on 2021-04-04 10:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=200, verbose_name='ФИО')),
                ('faculty', models.CharField(max_length=200, verbose_name='Факультет')),
                ('directon', models.CharField(max_length=200, verbose_name='Направление')),
                ('profile', models.CharField(max_length=200, verbose_name='Профиль')),
                ('topic', models.CharField(max_length=200, verbose_name='Тема ВКР')),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, verbose_name='Ключевые слова'), size=None)),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ('full_name',),
            },
        ),
    ]
