# Generated by Django 2.2.3 on 2021-04-07 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0002_auto_20210404_2022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
