# Generated by Django 2.2.3 on 2021-04-07 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0003_delete_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
