# Generated by Django 2.2.3 on 2021-04-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nlp', '0004_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=200, verbose_name='ФИО')),
                ('faculty', models.CharField(max_length=200, verbose_name='Факультет')),
                ('directon', models.CharField(max_length=200, verbose_name='Направление')),
                ('profile', models.CharField(max_length=200, verbose_name='Профиль')),
                ('topic', models.CharField(max_length=200, verbose_name='Тема ВКР')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ('full_name',),
            },
        ),
    ]
