# Generated by Django 3.2 on 2021-04-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0007_auto_20210417_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='report',
        ),
        migrations.AlterField(
            model_name='student',
            name='document',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
