# Generated by Django 3.2 on 2021-04-19 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0009_auto_20210419_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='faculty',
        ),
        migrations.AddField(
            model_name='direction',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nlp.department', verbose_name='Факультет'),
        ),
    ]
