# Generated by Django 3.2 on 2021-04-19 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0010_auto_20210419_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='departament',
        ),
        migrations.AlterField(
            model_name='direction',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nlp.department', verbose_name='Кафедра'),
        ),
    ]
