version: "3.3"

services:
  catalog:
    container_name: server
    build: ./server
    command: bash -c "python3 manage.py migrate --noinput && python3 manage.py runserver 0.0.0:8001"
    depends_on:
      - db
    ports:
      - 8001:8001

  db:
    image: postgres:11.1
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5434:5432

