# Generated by Django 3.2.4 on 2021-06-26 09:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cathedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='ФИО')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('vk_url', models.CharField(max_length=256, verbose_name='Ссылка на группу во Вконтакте')),
                ('dekan', models.CharField(max_length=128, verbose_name='Имя Декана')),
                ('faculties', models.ManyToManyField(to='web.Cathedra')),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('year_free_spots', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Данные POST запроса')),
                ('groups', models.ManyToManyField(to='web.Groups')),
            ],
        ),
        migrations.AddField(
            model_name='cathedra',
            name='directions',
            field=models.ManyToManyField(to='web.Direction'),
        ),
        migrations.AddField(
            model_name='cathedra',
            name='tags',
            field=models.ManyToManyField(to='web.Tag'),
        ),
        migrations.AddField(
            model_name='cathedra',
            name='teachers',
            field=models.ManyToManyField(to='web.Teacher'),
        ),
    ]
